### PR TITLE
Coding Standards Refactor and Minor Updates

### PR DESCRIPTION
**Pull request by majick777**
- WordPress coding standards refactoring for WP 5
- fixed the protocol in jQuery UI style Google URL
- reprefixed all functions for consistency (radio_station_)
- updated all the widget constructor methods
- merged the menu items into a single main menu
- updated the capability checks for the menu items
- moved the help and export pages to /templates/
- moved all the css files to /css/
- enqeued the djonair css from within the widget
- use plugins_url for all resource URLs 
- added $wpdb->prepare to sanitize a query
- added some sanization for metabox save values
- added a week and month translation helper
- added a radio station antenna icon

### CODE REVIEW

**Comment by tonyzeoli** [comment]
This is super awesome. I've responded to your email and have added you to the Netmix Slack Channel. Let's discuss and update you on the project status, where this is coming from, where I hope it goes, and answer your questions. I'm just getting up to speed with all of this as I just took over the plugin from someone else who hadn't updated in 3-years.

**Comment by nourmab13** [comment]
Woohoo!! I installed your updated version on my local site and it ROCKS!!  Luv the single main menu- great job, Mr. Majick777. I'm just getting started in WP (plug-in) development, and look forward to helping others just like you're doing!

**Comment by majick777** [comment]
@nourmab13 thanks for that, happy to be an inspiration on your journey. :-)

check out some of my other repos if you like, I have a few random and interesting projects, and a number of plugins more I'm still preparing for release. plus they use a few common library files now that help me keep development time down (eg. plugin loader - loader.php, sidebar helper - wordquest.php) so there might be some useful snippets in there to learn from.

but I digrees, if anyeone sees anything in these changes that needs explanation or fixing just let me know.

**Comment by tonyzeoli** [comment]
Hey all, after @nourmab13 confirmed she reviewed the code (nice to have a general code review anyway even though we don't have a formal process yet), I've merged the code into Master. I'll pull that done via Git to my Desktop, move it to my SVN version, then push it up to the rep. @majick777 Do you have any recommendations for assigning a version number, how to assign that version number, and other necessary steps to push this version up? This is my first ever time doing this, so I want to make sure that the user can see the version update on the repo and when they click the details of the plugin.

**Comment by tonyzeoli** [comment]
@majick777 I'm having an issue pulling down the code to local to move it to SVN. It says I have a conflict. I see in the header of the plugin duplicate references to the plugin details (owner, etc.)
Screen Shot 2019-07-17 at 5 44 19 PM
Screen Shot 2019-07-17 at 5 44 14 PM

**Pull request merged**
