### PR TITLE
WordPress coding standards and review

### PR DESCRIPTION
**Pull request by MikeNGarrett**
Hello netmix! 

Glad to have you adopting the plugin and making changes. We use this at [WRIR in Richmond, VA](http://www.wrir.org/). In order to continue using it, we have made changes over the years to support new versions of WordPress and PHP. 

This update includes our changes and follows [WordPress best practices](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) by using [phpcs](https://github.com/squizlabs/PHP_CodeSniffer) and the [coding standards library](https://github.com/WordPress/WordPress-Coding-Standards). I have included the `phpcs.xml` for this configuration.

### CODE REVIEW

**Comment by MikeNGarrett** [comment]
Added some additional commits based on my testing today. Current version 2.2.6. Let me know if you have any questions.

**Comment by tonyzeoli** [comment]
Hey @MikeNGarrett, awesome of you to come in and make these contributions. We're glad to put this plugin back in play and are hoping to add some new functionality ongoing. If you have any requests, please do add them to the Features requests list.

I am on vacation at the moment, but checking it out now and am asking @majick777 to take a look so that he's aware of how this may impact his future contributions. Can you let us know or give instructions as to how @majick777, who has been contributing code, should view this coding standards and review pull request and the addition of the xml file. What impact does that have on anything that he's contributing now or in the future? I'm asking these questions as the project manager, not as a developer, as that's my core contribution to this project - project management and product development.

I'll view the read me as well.

Thanks again. We appreciate it and welcome you to the project!

**Comment by tonyzeoli** [comment]
@MikeNGarrett I just went through almost everything and see where you've made many code changes to reflect best practices. I've set this on the Projects tab for @majick777 to review. Ongoing, I want to try to "comment" the code with the user who made the contribution and the date it was made. I'm not sure if in your experience that's a good idea or not, but please guide me in that regard so we can see in the code who made those contributions - that way if anyone has questions they know who made them and for which version.

**Comment by MikeNGarrett** [comment]
Happy to help out. As I said, most of these were made to continue supporting this plugin on WRIR's website and to support the technology running the website. 

**What impact does that have on anything that he's contributing now or in the future?**
It's recommended all code written for WordPress follows their standards (or at least some agreed-upon standards like PSR-2). It helps follow best practices and future-proof the code base. 

I provided links to the WordPress coding standards as well as the linter which has further information and instructions on how to implement these standards. This provides a set of standards everyone who contributes code can follow, including @majick777.

I don't recommend adding comments for contributions unless it's a major piece of functionality and you need to consult the person responsible when making changes down the road. A simple mention in the readme for the changes will do nicely in addition to the records you already with version control in github.

**Comment by tonyzeoli** [comment]
Great, thanks for the direction. I will merge the pull request now and upload the latest version to netmix.co/radio-station-demo tomorrow for testing.

I really appreciate you coming in to clean this up with coding standards. That is so awesome.

BTW, I'm talking with LibreTime about a Radio Station / LibreTime integration so that LibreTime pushes content and the audio stream into Radio Station via API. Maybe a long way out, but that's going to be a very cool integration if it comes to fruition.

**Comment by MikeNGarrett** [comment]
Sounds good. Thanks for the info.

**Comment by tonyzeoli** [comment]
@MikeNGarrett There may be an issue with 2.2.6. Users are reporting a bug. See: https://github.com/netmix/radio-station/issues/43

Can you please check and let me know why the require in radio-station.php isn't seeing the post-type.php file?

**Comment by tonyzeoli** [comment]
Looks like there are files not named correctly in radio-station.php according to one user here. It's working for me, so not sure why it's not working for them.

https://wordpress.org/support/topic/2-2-6-triggers-a-fatal-error/#post-11861876

**Comment by tonyzeoli** [comment]
@MikeNGarrett one user reported that the file name for the includes should have "wiget" and not "class" in them. But I took at a look at radio-station.php on Line 57 and see that the includes are named correctly in the file and in the /includes folder. Am I doing something wrong here? I tested this on https://netmix.com/radio-station-demo and I'm not seeing an error. So, I'm not sure what the issue is.

**Comment by MikeNGarrett** [comment]
The files on the WordPress svn repo (wordpress.org) aren't correct. See the difference?
Screen Shot 2019-08-23 at 5 33 23 PM

**Comment by tonyzeoli** [comment]
I got it now. When I copied the files into SVN, it didn't remove the old files. Since I copied in and did not actually delete everything in trunk first, It kept the widget files and doesn't remove them. I'm working on solving this now.

**Comment by tonyzeoli** [comment]
I've committed the class files, but they're just not showing up in the download. I tried to readd the widget files to git and then delete them and move the includes folder back into svn for commit, but it says there's nothing changed to commit. So, I'm kind of stuck.

**Comment by MikeNGarrett** [comment]
I'm not sure. It sounds like a svn issue. You may need svn move or to reset the changes from a feature branch.

**Comment by tonyzeoli** [comment]
okay, I'm trying to figure it out, thanks. This is all new and I didn't set a branch for earlier versions nor a tag and I'm learing about those now. I'll figure it out though...I always do.

**Comment by MikeNGarrett** [comment]
I highly recommend the following for reference:
https://developer.wordpress.org/plugins/wordpress-org/how-to-use-subversion/
http://svnbook.red-bean.com/

**Comment by tonyzeoli** [comment]
Yep, I've been looking at that already, thanks.

**Comment by tonyzeoli** [comment]
Okay, I'm all set. I figured it out. Whew! 2.2.6 is now downloading correctly. There was nothing in the trunk for a bit today. I finally figured out Versions App, where you need to make sure to click "Add" for each folder or file if you've already committed. Somehow the trunk went empty, so I'm good. Now, I need to "tag" this version.

**Comment by majick777** [comment]
@MikeNGarrett Thanks for all the excellent contribution! It is much appreciated. Definitely great to have another set of eyes looking over this. Did my best on first round of cleanup to bring up to coding standards but glad you've pushed it further. 

Just did another bugfix and enhancement stint today. A few things worthy of mention on this front that I picked up and have added to the next release. 
- I reverted the anonymous function usage on the registration widget actions. SInce this is quite an old plugin there is a risk there are users who are on really old PHP versions and until WordPress officially changes to PHP 5.3 minimum. But besides that It also means actions can be unhooked by users more easily if they have a proper function name, however unlikely that is, I think it is better practice for consisitency..
- I fixed the weekday and month locations to use the WP_Locale class for this purpose. For future note variable translations are not picked up by translation software so we can't do anything like `__( $string, 'radio-station');` See: http://ottopress.com/tag/translation/ "Law of the First"

I checked out the diff before the last release but didn't have time to communicate then, everything else looks peachy so far, just picked these up today.

I'm probably a bit over-enthusiastic with code commenting to help with clarity and ease of contribution tcompared to coding standards. It is good to keep close to those, but at the same time better practice goes beyond standards, so we needn't be as strict on syntax as for core or a theme. (My over-ambitious escaping was from recent work on a theme, lol.)

Like this may be a pet peev but thought I'd mention so we don't keep changing each other's formating back and forth I really like to avoid this for short lines:

``if ( $condition ) {``
``        do_something();}``

The end bracket here makes condition blocks harder to read visually when checking through to see if everything is closed properly. So prefer to keep in one clean line or if needs be:

``if ( $condition ) {``
``       do_something();``
``}``

Thanks again for the great commit. Let us know if there are other issues you want to help us tackle. The current list is sorted via the Projects tab into Bugfixes, Enhancements and Features. The bugfixes have been cleared and have made some headway on some enhancements and will be pushing 2.2.7 shortly. :-)

**Pull request merged**
